local config = {
  defaults = {
    theme = 'auto',
    transparent = false,
    dim_inactive = false,
    terminal_colors = true,
    no_italic = false,
    no_bold = false,
    no_underline = false,
    no_undercurl = false,
    italics = {
      comments = true,
      keywords = true,
      functions = true,
      strings = true,
      variables = true,
      bufferline = false,
    },
    styles = {
      comments = {},
      keywords = {},
      functions = {},
      strings = {},
      variables = {},
      numbers = {},
      booleans = {},
      types = {},
      operators = {},
      properties = {},
    },
    on_colors = nil,
    on_highlights = nil,
    integrations = {
      telescope = true,
      gitsigns = true,
      which_key = true,
      neo_tree = true,
      trouble = true,
      noice = true,
      flash = true,
      notify = true,
      render_markdown = true,
      indent_blankline = true,
      lspsaga = true,
      lazy = true,
      mason = true,
      dashboard = true,
      oil = true,
      dap = true,
      mini = true,
      fidget = true,
      navic = true,
      illuminate = true,
      hop = true,
      copilot = true,
      aerial = true,
      snacks = true,
    },
    overrides = {},
  },
}

setmetatable(config, { __index = config.defaults })

return config
