local M = {}

function M.highlights(c, config, utils)
  return {
    LspReferenceText = { bg = c.menuOptionBackground },
    LspReferenceRead = { bg = c.menuOptionBackground },
    LspReferenceWrite = { bg = c.menuOptionBackground },
    LspCodeLens = { fg = c.commentText },
    LspCodeLensSeparator = { fg = c.commentText },
    LspSignatureActiveParameter = {
      bg = utils.shade(c.warningEmphasis, 0.5, c.editorBackground),
      bold = true,
    },
    LspInlayHint = { fg = c.commentText },
    LspInfoTip = { fg = c.commentText },
    LspInfoList = { fg = c.mainText },
    LspInfoFiletype = { fg = c.syntaxKeyword },
    LspInfoBorder = { fg = c.windowBorder },
    ['@lsp.type.namespace'] = { link = '@namespace' },
    ['@lsp.type.type'] = { link = '@type' },
    ['@lsp.type.class'] = { link = '@type' },
    ['@lsp.type.enum'] = { link = '@type' },
    ['@lsp.type.enumMember'] = { fg = c.syntaxFunction },
    ['@lsp.type.interface'] = { fg = c.syntaxInterface },
    ['@lsp.type.struct'] = { link = '@type' },
    ['@lsp.type.parameter'] = { link = '@parameter' },
    ['@lsp.type.property'] = { link = '@property' },
    ['@lsp.type.function'] = { link = '@function' },
    ['@lsp.type.method'] = { link = '@method' },
    ['@lsp.type.macro'] = { link = '@label' },
    ['@lsp.type.decorator'] = { link = '@label' },
    ['@lsp.type.variable'] = { link = '@variable' },
    ['@lsp.type.event'] = { link = '@label' },
    ['@lsp.type.keyword'] = { link = '@keyword' },
    ['@lsp.type.modifier'] = { link = '@keyword' },
    ['@lsp.type.comment'] = { link = 'Comment' },
    ['@lsp.type.string'] = { link = '@string' },
    ['@lsp.type.number'] = { link = '@number' },
    ['@lsp.type.boolean'] = { link = '@boolean' },
    ['@lsp.type.regexp'] = { link = '@string.regexp' },
    ['@lsp.type.operator'] = { link = '@operator' },
    ['@lsp.typemod.function.declaration'] = { link = '@function' },
    ['@lsp.typemod.function.readonly'] = { link = '@function' },
    ['@lsp.typemod.function.defaultLibrary'] = { link = '@function.builtin' },
    ['@lsp.typemod.variable.readonly'] = { link = '@constant' },
    ['@lsp.typemod.variable.global'] = { link = '@variable.builtin' },
    ['@lsp.typemod.variable.defaultLibrary'] = {
      link = '@variable.builtin',
    },
    ['@lsp.typemod.variable.declaration'] = { link = '@variable' },
    ['@lsp.typemod.property.readonly'] = { link = '@constant' },
    ['@lsp.typemod.property.declaration'] = { link = '@property' },
    ['@lsp.typemod.parameter.readonly'] = { link = '@constant' },
    ['@lsp.typemod.parameter.declaration'] = { link = '@parameter' },
    ['@lsp.typemod.type.defaultLibrary'] = { link = '@type.builtin' },
    ['@lsp.typemod.method.declaration'] = { link = '@function' },
    ['@lsp.mod.deprecated'] = { strikethrough = true },
    ['@lsp.mod.readonly'] = { link = '@constant' },
    ['@lsp.mod.defaultLibrary'] = { italic = true },
  }
end

return M
