local M = {}

function M.highlights(c, config, utils)
  return {
    ['@text'] = { fg = c.mainText },
    ['@markup.strong'] = { link = 'Bold' },
    ['@markup.strikethrough'] = { strikethrough = true },
    ['@markup.italic'] = { link = 'Italic' },
    ['@markup.heading'] = { link = 'Keyword' },
    ['@markup.link.url'] = {
      fg = c.syntaxFunction,
      sp = c.syntaxFunction,
      underline = true,
    },
    ['@markup.underline'] = { link = 'Underlined' },
    ['@markup.link'] = { fg = c.linkText },
    ['@markup.list'] = { fg = c.syntaxOperator },
    ['@markup.quote'] = { fg = c.commentText },
    ['@markup.heading.1'] = { fg = c.syntaxFunction, bold = true },
    ['@markup.heading.2'] = { fg = c.syntaxKeyword, bold = true },
    ['@markup.heading.3'] = { fg = c.linkText, bold = true },
    ['@markup.heading.4'] = { fg = c.warningText, bold = true },
    ['@markup.heading.5'] = { fg = c.specialKeyword, bold = true },
    ['@markup.heading.6'] = { fg = c.syntaxError, bold = true },
    ['@symbol'] = { fg = c.syntaxOperator },
    ['@comment.todo'] = { link = 'Todo' },
    ['@comment.error'] = { fg = c.errorText },
    ['@comment.warning'] = { fg = c.warningText },
    ['@comment.note'] = { fg = c.syntaxFunction },
    ['@comment'] = { link = 'Comment' },
    ['@punctuation'] = { link = 'Punctuation' },
    ['@punctuation.bracket'] = { fg = c.warningEmphasis },
    ['@punctuation.delimiter'] = { fg = c.syntaxError },
    ['@punctuation.terminator.statement'] = { link = 'Delimiter' },
    ['@punctuation.special'] = { fg = c.syntaxError },
    ['@punctuation.separator.keyvalue'] = { fg = c.syntaxError },
    ['@diff.plus'] = { fg = c.successText },
    ['@diff.minus'] = { fg = c.errorText },
    ['@diff.delta'] = { fg = c.warningText },
    ['@constant'] = { link = 'Constant' },
    ['@constant.builtin'] = { fg = c.syntaxFunction },
    ['@constant.macro'] = { link = 'Keyword' },
    ['@string'] = { link = 'String' },
    ['@string.escape'] = { fg = utils.shade(c.stringText, 0.45) },
    ['@string.special'] = { fg = utils.shade(c.syntaxFunction, 0.45) },
    ['@number'] = { link = 'Number' },
    ['@boolean'] = { link = 'Boolean' },
    ['@function'] = {
      link = 'Function',
      italic = config.italics.functions or false,
    },
    ['@function.call'] = { link = 'Function' },
    ['@function.builtin'] = { link = 'Function' },
    ['@parameter'] = { link = 'Parameter' },
    ['@method'] = { link = 'Function' },
    ['@field'] = { link = 'Property' },
    ['@property'] = { link = 'Property' },
    ['@constructor'] = { fg = c.syntaxFunction },
    ['@label'] = { link = 'Label' },
    ['@operator'] = { link = 'Operator' },
    ['@exception'] = { link = 'Exception' },
    ['@variable'] = {
      fg = c.syntaxFunction,
      italic = config.italics.variables or false,
    },
    ['@variable.builtin'] = { fg = c.syntaxFunction },
    ['@variable.member'] = { fg = c.mainText },
    ['@variable.parameter'] = {
      fg = c.mainText,
      italic = config.italics.variables or false,
    },
    ['@type'] = { link = 'Type' },
    ['@type.definition'] = { fg = c.mainText },
    ['@type.builtin'] = { fg = c.syntaxFunction },
    ['@type.qualifier'] = { fg = c.syntaxFunction },
    ['@keyword'] = { link = 'Keyword' },
    ['@namespace'] = { link = 'Type' },
    ['@annotation'] = { link = 'Label' },
    ['@debug'] = { fg = c.specialKeyword },
    ['@tag'] = { link = 'Tag' },
    ['@tag.builtin'] = { link = 'Tag' },
    ['@tag.delimiter'] = { fg = c.syntaxOperator },
    ['@tag.attribute'] = { fg = c.syntaxKeyword },
    ['@tag.jsx.element'] = { fg = c.syntaxFunction },
    ['@attribute'] = { fg = c.syntaxKeyword },
    ['@error'] = { link = 'Error' },
    ['@warning'] = { link = 'WarningMsg' },
    ['@info'] = { fg = c.syntaxFunction },
    ['@label.json'] = { fg = c.syntaxFunction },
    ['@label.help'] = { link = '@markup.link.url' },
    ['@markup.link.url.html'] = { underline = true },
    ['@markup.raw'] = { bg = 'NONE' },
    ['@markup.raw.block'] = { bg = 'NONE' },
    ['@text.literal'] = { bg = 'NONE' },
    ['@text.literal.block'] = { bg = 'NONE' },
    markdownCode = { bg = 'NONE' },
    markdownCodeBlock = { bg = 'NONE' },
    markdownCodeDelimiter = { bg = 'NONE' },
    markdownCodeInline = { bg = 'NONE' },
    RenderMarkdownCode = { fg = c.mainText, bg = 'NONE' },
    RenderMarkdownCodeBorder = { bg = 'NONE' },
    RenderMarkdownCodeInfo = { fg = c.inactiveText, bg = 'NONE' },
    RenderMarkdownCodeFallback = { bg = 'NONE' },
    RenderMarkdownCodeInline = { fg = c.mainText, bg = 'NONE' },
    RenderMarkdownInlineHighlight = { bg = 'NONE' },
    NotifyBackground = { bg = c.floatingWindowBackground },
    NotifyINFOIcon = { fg = c.syntaxFunction },
    NotifyINFOTitle = { fg = c.syntaxFunction },
    NotifyINFOBody = { fg = c.mainText },
    NotifyWARNIcon = { fg = c.warningText },
    NotifyWARNTitle = { fg = c.warningText },
    NotifyWARNBody = { fg = c.mainText },
    NotifyERRORIcon = { fg = c.syntaxError },
    NotifyERRORTitle = { fg = c.syntaxError },
    NotifyERRORBody = { fg = c.mainText },
    NotifyDEBUGIcon = { fg = c.syntaxOperator },
    NotifyDEBUGTitle = { fg = c.syntaxOperator },
    NotifyDEBUGBody = { fg = c.mainText },
    NotifyTRACEIcon = { fg = c.linkText },
    NotifyTRACETitle = { fg = c.linkText },
    NotifyTRACEBody = { fg = c.mainText },
  }
end

return M
